### ISSUE TITLE
SITRA - Limit to 100

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1148]
Après discussion avec l'équipe SITRA, il y a une limite de 100 objets sur les flux.

La discussion ci-dessous : 

MOI : Par contre, il y a une limite à 100 ?
http://api.sitra-tourisme.com/api/XXXXXXX}

Ou alors je peux changer "count":200 ?
Car ma sélection renvoie normalement 101 éléments pour le moment... et potentiellement plus dans le futur.

SITRA : Les API sont limitées à 100 objets à la fois. Ton site internet doit faire plusieurs requêtes si le nombre d'objets dépasse 100...

**Comment by gutard** [comment]
The new import framework is able to handle paginated results

**Comment by camillemonchicourt** [comment]
OK good point that it works for SITRA import in TOURISTIC CONTENTS.
But it still dont works with SITRA used as EXTERNAL DATASOURCE ?

**Comment by gutard** [comment]
I think external datasource is superseded by import into touristic contents or trek infos.

**Comment by camillemonchicourt** [comment]
Hum as we talked about it is not really the same thing. 
We can display all HUTS from the national park as an information layer (external datasource coming from SITRA) without including them in our Accomodation category where we will promote the PNE label accomodations.

**Comment by gutard** [comment]
You can create two categories of touristic contents : one for huts from SITRA and one other for accommodations from "Esprit Parc Naturel" database.
