### ISSUE TITLE
Altimetric profile : vertical scale

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek#1155]
When distance is long and altitude variation is short, the scale should reflect the reality instead of stetching vertically :

![den](https://cloud.githubusercontent.com/assets/546692/3644248/589ee242-10de-11e4-993d-2189c9cb3003.png)

Use the same scale for horizontal and vertical axis.

**Comment by gutard** [comment]
With v0.34.0 there is a minimum of 1000 meters in vertical scale. It seems difficult to fix horizontal scale as trek length may vary from less than 1 km to more than 100 km.
