### ISSUE TITLE
Livret fiche pdf

### ISSUE THREAD

**Issue by fmerzeau** [makinacorpus/Geotrek#1163]
Y-a t'il une possibilité que l'export pdf des fiches itinéraires se fasse sous la forme d'un livret pliable numéroté ?
Je pense que c'est assez compliqué a réaliser.
Est-ce prévu dans #1120 ?

**Comment by camillemonchicourt** [comment]
Dans la V2, le système d'import a été revu et se base désormais sur un template HTML à partir duquel WeasyPrint génère le PDF. 
Alors qu'il était encore possible d'utiliser le template ODT jusqu'à la version 2.10.4, à partir de celle-ci le template HTML est désormais activé par défaut et le template ODT n'est plus utilisé. 
Voir https://github.com/makinacorpus/Geotrek/issues/1589 pour plus d'infos. 

Le PDF se base sur un format A4 mais a été conçu pour pouvoir bien s'imprimer et être lisible si l'utilisateur choisit de l'imprimer au format LIVRET.
