### ISSUE TITLE
Echelle de la carte sur les exports fiches itinéraires

### ISSUE THREAD

**Issue by fmerzeau** [makinacorpus/Geotrek#1182]
Je viens de faire la màj vers la v0.26.2. Je constate que l'échelle a été réduite, ce qui nuit à la lisibilité de l'itinéraire. Est-ce possible de gérer ce paramètre ?
Exemple sur 0.25.1
![trek-897 v 0 25 1](https://cloud.githubusercontent.com/assets/7872468/4095223/830947ce-2fb1-11e4-8724-86a1aef43c45.JPG)

Exemple sur 0.26.2
![trek-897 v 0 26 2](https://cloud.githubusercontent.com/assets/7872468/4095225/84fb1904-2fb1-11e4-8523-8400e8e56639.JPG)

**Comment by gutard** [comment]
Fixed in 0.28.6

**Comment by camillemonchicourt** [comment]
Confirmed that MAPS are OK after installing 0.29.0 ! Thanks.

**Comment by leplatrem** [comment]
\o/ GG !
