### ISSUE TITLE
EDITION rights by structure

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1219]
Actually each user is attached to a structure. 
Users can only EDIT paths, trails, infrastructures, signages, interventions, projects created by one user of his structure. 
It would be interesting to have the same possibility with TREKS and POIs.

It would need to be a setting as some may want to have no structure right distinctions for TREKS and POIs (such as PNM/PNAM).

**Comment by gutard** [comment]
@camillemonchicourt I suppose touristic contents and events should be structure related too

**Comment by gutard** [comment]
My bad. It's already done.

**Comment by camillemonchicourt** [comment]
Good point !
