### ISSUE TITLE
Keep colors and formating from HTML fields in PDF export

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek#1237]
Currently, we convert the text fields to plain text before inserting them in the ODT template.

Mainly because Appy does not keep the Justify alignment when inserting XHMTML : please read https://bugs.launchpad.net/appy/+bug/1361165

Also, it is not easy to keep a link between HTML styles (span colors) and ODT styles : please read
https://bugs.launchpad.net/appy/+bug/1361166

This would be very useful though, to keep URL links, red color for trek marks descriptions etc.

Related #1105 #1235

**Comment by leplatrem** [comment]
Good news everyone!

Gaetan contributed a fix to Appy.pod that will preserve **justified text** in HTML blocs in PDF exports:
https://bugs.launchpad.net/appy/+bug/1361165

That would require to upgrade Appy.pod, and remove the piece of code that converts blocs to plain texts. This way bold, italic and colors will also be preserved :)

+++

**Comment by camillemonchicourt** [comment]
Very good news indeed  !

**Comment by gutard** [comment]
OK with weasyprint.
