### ISSUE TITLE
Script to add to improve synchro / Ajout d'un script pour faciliter la synchronisation

### ISSUE THREAD

**Issue by celine971** [makinacorpus/Geotrek#1261]
------------PNG/N.Martinon
* Ajout d'un script pour faciliter la synchonisation
-------------------------------------------------------------
  - Fichier : synchro
  - Contenu :
#!/bin/bash 
if [ "$(id -u)" != "0" ]; then 
   echo "Seul l'utilisateur root peut exécuter ce script" 1>&2 
   echo "La commande doit être 'sudo $0'" 1>&2 
   exit 1 
fi 

cd Geotrek-rando 
make sync 
service apache2 restart 
cd ..
  - Usage : Après connexion ssh, exécuter la commande "sudo ./synchro"
-------------------------------------------------------------
NB : Makina/M. Leplatre
-- Le restart d'Apache n'est nécessaire que pour vider le cache HTML qui est d'1H
-- Ajouter un directive dans le fichier Makefile pour pouvoir faire sudo make sync restart

**Comment by camillemonchicourt** [comment]
Only for V1.X
Synchro changed in V2.X
