### ISSUE TITLE
Itinéraire impossible à enregistrer

### ISSUE THREAD

**Issue by Pisenmann** [makinacorpus/Geotrek#1291]
De manière systématique, le tracé d'un itinéraire s'exécute (topo OK) mais refuse d'être enregistré (http://XXXX/trek/edit/15345/) avec ce message : "message : 504 Gateway Time-out."
- le fichier log d'erreur est vide...
- plus de 14 tronçons forment cet itinéraire...
- plusieurs tronçons n'ont pas de données MNT (au traçage de certains tronçons, le profil alti indiquait "no data")...

![sel](https://cloud.githubusercontent.com/assets/9135663/4933218/0078000c-6594-11e4-8cf0-0ea00b3ebaec.JPG)

i don't anderstand what happened !

**Comment by camillemonchicourt** [comment]
Fixed in 0.28.5 - https://github.com/makinacorpus/Geotrek/releases/tag/v0.28.5
Fix DEM optimizations when minimum elevation is zero
