### ISSUE TITLE
Event errors while editing paths

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1328]
A user was trying to edit a path yesterday. 
Each time he saved the path changes he had these errors : 

InternalError: line_locate_point: 2st arg isnt a point
CONTEXT:  PL/pgSQL function "st_interpolatealong" line 9 at assignment
SQL statement "SELECT *                                 FROM ST_InterpolateAlong(NEW.geom, egeom) AS (position float, distance float)"
PL/pgSQL function "update_evenement_geom_when_troncon_changes" line 22 at SQL statement

ALSO got this error : 

InternalError: line_locate_point: 2st arg isnt a point
CONTEXT:  PL/pgSQL function "st_interpolatealong" line 9 at assignment
SQL statement "SELECT *                                 FROM ST_InterpolateAlong(NEW.geom, egeom) AS (position float, distance float)"
PL/pgSQL function "update_evenement_geom_when_troncon_changes" line 22 at SQL statement
SQL statement "UPDATE l_t_troncon SET geom = segment WHERE id = troncon.id"
PL/pgSQL function "troncons_evenement_intersect_split" line 151 at SQL statement

This path had 2 signages so I moved them to another path, but still had the error. So it may was due to other events (trails, zoning...) but couldnt find the reason and sadly the user removed this path and created a new one. :-)

**Comment by gutard** [comment]
Fixed in 0.29.0
