### ISSUE TITLE
0.28.4 - Unable to generate maps ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1331]
Je ne sais pas si c'est lié à la 0.28 ?

Je n'arrive plus rien à synchroniser Geotrek-rando avec Geotrek-admin depuis une petite semaine.
Mon répertoire `/home/sentiers/Geotrek/var/media/maps` est vide car j'avais tout supprimé pour voir si ça pouvait régler le problème.
Quand je lance un `MAKE SYNC`, il bloque toujours sur la génération du premier PDF : 

```
/fr/api/trek/trek-903486.pdf ... 504 (Failed)
Failed to retrieve http://XX.XX.XXX.147/api/trek/trek-903486.pdf (code: 504)
Failed!
```

Il envoie un email : [Geotrek] ERROR: Request on http://127.0.0.1:6543/?url=http%3A//XX.XX.XXX.147/document/print-trek-903486.odt&to=application/pdf failed (status=504)

```
Traceback (most recent call last):

  File "/home/sentiers/Geotrek/lib/eggs/mapentity-1.10.1-py2.7.egg/mapentity/helpers.py", line 148, in download_to_stream
    assert source.status_code == 200, status_error

AssertionError: Request on http://127.0.0.1:6543/?url=http%3A//XX.XX.XXX.147/document/print-trek-903486.odt&to=application/pdf failed (status=504)
```

Et un autre email : [Geotrek] CRITICAL: WORKER TIMEOUT (pid:5815)

Et il créé un fichier `trek-903486.png` de 0 Ko dans `/home/sentiers/Geotrek/var/media/maps`

Si j'essaie de lancer la génération des cartes en commande :

```
xxxx@xxxx:~$ cd Geotrek
xxxx@xxxx:~/Geotrek$ bin/django prepare_map_images --url=http://XX.XX.XXX.147 
```

Il créé un premier fichier `path-2758.png` de 0 Ko dans `/home/sentiers/Geotrek/var/media/maps`

Dans Putty, il reste sur : 

```
INFO 2014-12-03 12:51:32,380 mapentity Generate map images for model <class 'geotrek.core.models.Path'>
INFO 2014-12-03 12:51:32,475 mapentity.helpers Request to: http://127.0.0.1:8001/?url=http%3A//XX.XX.XXX.147/path/2758/%3Fcontext%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520555.0078388920704%252C%2520%2522height%2522%253A%2520800%257D%257D&selector=.map-panel&waitfor=.leaflet-tile-loaded
INFO 2014-12-03 12:51:32,488 requests.packages.urllib3.connectionpool Starting new HTTP connection (1): 127.0.0.1
```

Même depuis Geotrek-admin, impossible d'exporter quelconque fiche car il arrive pas à générer les images des cartes.
Un aménagement par exemple.
Mon répertoire `/home/sentiers/Geotrek/var/media/maps` est vide. Il créé un fichier de 0 ko (exemple `infrastructure-920082.png`) quand je demande un export.

**Comment by camillemonchicourt** [comment]
Fixed ?

**Comment by gutard** [comment]
Not really fixed as we cannot identify a commit that solves the problem but not reproduced so we can close.

**Comment by camillemonchicourt** [comment]
Yes !
