### ISSUE TITLE
Treks - Add source field

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1354]
We are actually working on adding some additional treks from some partners.
A field SOURCE (or author) would be useful to keep the information (and maybe show it on Geotrek-rando) of who wrote this trek.
It could also be useful when we export some treks with others (Sitra, IGN...) to be able to filter to only send only our treks.

**Comment by camillemonchicourt** [comment]
This field would need to be N-N with a list of structures.

**Comment by gutard** [comment]
This is very similar to the notion of "maître d'ouvrage" request by PNC.

**Comment by camillemonchicourt** [comment]
I dont know about this notion, but this is to be discuted. 
As there should not be "maitre d'ouvrage" on TREKS. This is not related to TREKS but to PATHS.
There are manager for signages and works fro PATHS through STATUTS module.

**Comment by gutard** [comment]
I think what PNC calls "maître d'ouvrage" is what you call "author". This more the naming than the notion that hurts you. In this case the "ouvrage" refers to the virtual existence of the trek (its creation, its conception). Not the physical one (which is actually covered by the statuts module). @camillemonchicourt, please discuss with @amandine-sahl to explicit the concept and choose the right name.

**Comment by camillemonchicourt** [comment]
Yes, we scheduled discuss it this afternoon. 
Thanks.

**Comment by leplatrem** [comment]
My two cents: in the OpenTrail spec there is a notion of operator
Le 19 févr. 2015 11:56, "Camille Monchicourt" <notifications@github.com> a
écrit :

**Comment by camillemonchicourt** [comment]
OK donc discuté avec @amandine-sahl
En effet sur les randos c'est bien la source des contenus qui nous intéresse (N-N). Les gestionnaires du linéraire sont des infos saisies au niveau des statuts et que l'on ne souhaite pas faire remonter sur Geotrek-Rando sur les randos.

Par contre la notion de gestionnaire (remplaçant le terme de maître d'ouvrage) est une info que le PNC (et nous du coup) souhaite ajouter sur les objets touristiques avec une liste déroulante N-N.
Un gestionnaire = Un nom, une description, un logo.

**Comment by gutard** [comment]
OK donc pour résumer 2 notions différentes:
- la source sur les itinéraires,
- le gestionnaire sur les contenus touristiques.
C'est bien ça ?

@camillemonchicourt, pour la source, tu parles de pointer vers une structure. Or les structures, ça existe déjà dans Geotrek et les itinéraires sont déjà liés aux structures. Il faut rajouter une bibliothèque supplémentaire ?

**Comment by camillemonchicourt** [comment]
Oui et on a aussi une liste d'organismes gestionnaires. 
J'en discute ici et je te dis rapidement.

**Comment by gutard** [comment]
J'ai ouvert le ticket #1396 pour tracer la notion de gestionnaire et recentrer ce ticket sur la notion de source. L'idée est d'ajouter un champ source en texte libre sur les différents contenus, utilisable à convenance par exemple pour tracer l'origine d'un contenu importé et/ou son identifiant externe.

**Comment by camillemonchicourt** [comment]
OK, on regarde ça aujourd'hui.

**Comment by camillemonchicourt** [comment]
On en a reparlé avec Pierrick et ça nous semble pas encore très clair.
La notion de SOURCE nous parait interessante sur les ITINERAIRES. 
Mais aussi sur les OBJETS et EVENEMENTS TOURISTIQUES. Là aussi la source de la donnée (PNE, COMCOM A, OT B, SITRA...) nous parait plus interessante que le GESTIONNAIRE qui fait un peu doublon avec les informations sur le CONTACT.

D'autant plus que le PnC souhaitait intégrer une notion de Workflow de validation pour que des partenaires puissent saisir directement dans leur Geotrek-admin. Il y a aussi peut-être un lien à faire avec cela....

Donc... il faut qu'on reboucle avec le PnC et @amandine-sahl ...

**Comment by gutard** [comment]
En fait il existe déjà une table Datasource (l_b_source) utilisée pour les tronçons. Je peux l'étendre facilement aux itinéraires, POIs, contenus et événements touristiques.

En ce qui concerne la notion de gestionnaire, il est préférable de commenter le bug #1396 plutôt que celui-ci.

**Comment by camillemonchicourt** [comment]
Oui OK, on en a parlé hier avec le PNC, on confirme dans la semaine

**Comment by camillemonchicourt** [comment]
OK donc on a rebouclé sur les 2 notions. 
On retombe sur le même besoin et tout le monde est d'accord sur : 

- c'est bien la SOURCE DE LA DONNÉE qui nous intéresse et non le GESTIONNAIRE de l'objet (que l'on a déjà sur les tronçons avec le module STATUT pour le linéaire OU avec l'info CONTACT sur les objets et événements touristiques).
- on abandonne donc la notion de GESTIONNAIRE SUR LES CONTENUS TOURISTIQUES (https://github.com/makinacorpus/Geotrek/issues/1396).
- on souhaite donc pouvoir renseigner la SOURCE DE LA DONNÉE sur les itinéraires, contenus touristiques et événements touristiques. Pas besoin sur les POI.
- on ne peut pas utiliser la table l_b_source car elle n'a rien à voir, elle liste des sources de données pour les tronçons uniquement (BD topo, numérisation sur SCAN 25, sur ortho, relevé GPS...) alors que là on va vouloir associer les itinéraires et contenus touristiques à des organismes ou personnes à l'origine des textes. 
- on ne peut pas utiliser la table des structures car celle-ci est étroitement aux utilisateurs qui accèdent à l'appli et à leurs droits. Donc pas grand chose à voir non plus.
- il nous parait donc nécessaire de créer une autre table et de la relier en N-N aux itinéraires, objets et événements touristiques. Celle-ci contiendra la NOM de la source, son LOGO et une URL (utilisable sur les fiches détails).
- Pour différencier cette table de L_B_SOURCE, on peut renommer celle-ci en L_B_SOURCE_TRONCON ou L_B_SOURCE_NUMERISATION et appeler la nouvelle O_B_SOURCE_FICHE. Ou sinon garder L_B_SOURCE pour les tronçons et nommer la nouvelle O_B_PRODUCTEUR mais ce nom peut porter à confusion lors de la saisie.

**Comment by camillemonchicourt** [comment]
We said that SOURCE should be N-N relation and it was developped as 1-N.
Is that OK ?

**Comment by gutard** [comment]
I just forgot this point

**Comment by camillemonchicourt** [comment]
Can be closed with https://github.com/makinacorpus/Geotrek/releases/tag/v0.33.1 ???
