### ISSUE TITLE
ZONING cache ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1361]
I removed all ZONING from the adminsite in order to update every ZONING in our Geotrek.

I worked on the new layer and then uploaded it in l_zonages_reglementaires.
It worked well and segmentation with every objects was well done.

But when I display the layers in Geotrek, it still shows the old zoning limits (while intersections with objects are OK).

Natura2000 in Geotrek : 

![n2000-geotrek](https://cloud.githubusercontent.com/assets/4418840/6151791/71841a26-b218-11e4-8495-a91fec3cb2ef.jpg)

When I display the Geotrek layer in QGIS (l_zonages_reglementaires), the limits are OK : 

![n2000-qgis](https://cloud.githubusercontent.com/assets/4418840/6151794/73b6cbea-b218-11e4-812c-2be110d03df4.jpg)

I dont understand how Geotrek can show the old limits that were deleted through adminsite...

I try to remove my browser cache, to reboot the server, to remove memcache (sudo service memcached restart), to restart controllers (bin/supervisorctl restart all) but it is still the same.

**Comment by gutard** [comment]
Remove var/cache/ directory content (Geotrek one, not system one!) and then clear browser cache.

**Comment by camillemonchicourt** [comment]
Thanks, it worked even without clearing browser cache. 
Good to know !

**Comment by leplatrem** [comment]
Yes those data are considered too big to be stored in memcache... So we chose to persist them on disk

**Comment by camillemonchicourt** [comment]
OK
