### ISSUE TITLE
EXPORT CSV - Use comas for decimals

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1366]
In CSV exports, some fields use comas for decimals. Such as LENGTH field so this field are working well when we open the CSV in LibreOffice Calc adn do a sum for example.

But many other numeric fields are exported with a POINT for decimals. Such are COSTS, 
HEIGHT, AREA, MAN-DAY, HEIGHT DIFFERENCE... 

So we cant do any calculation on this fields when working in CALC.

**Comment by gutard** [comment]
Actually it should depend on locale (fr -> coma, en -> point). Anyway it should consistent for all fields.

**Comment by camillemonchicourt** [comment]
Yes !
