### ISSUE TITLE
Translate boolean values in csv exports

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1380]

**Comment by gutard** [comment]
@camillemonchicourt, do you prefer:
- true/false (vrai/faux) ?
- yes/no (oui/non) ?
- 0/1 ?
- <blank>/X ?

**Comment by camillemonchicourt** [comment]
yes/no will certainly be the most understandable for users. 


All fields in CSV export should also be in SHP exports but I think when it is done for one it goes to the other too ? 


Thanks

**Comment by gutard** [comment]
Yes

**Comment by gutard** [comment]
Fixed in 0.31.0
