### ISSUE TITLE
ERROR EMAIL - Error creating geometry from value

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1381]
Received this error email, not sure if it is related to https://github.com/makinacorpus/Geotrek/issues/1224

**SUBJECT :**
[Geotrek] ERROR: Error creating geometry from value '"{ \"type\": \"LineString\", \"coordinates\": [ [ 6.072340149933417, 44.981156433173716 ], [ 6.072159303283178, 44.980940671891886 ], [ 6.072150563714361, 44.980810260854632 ], [ 6.072139409078441, 44.980621348192322 ], [ 6.072224248781811, 44.980533404396262 ], [ 6.07213519040042, 44.980414222891596 ], [ 6.072157283741305, 44.980368559940985 ], [ 6.072249941604384, 44.980307431670859 ], [ 6.072319129854323, 44.980237941242741 ], [ 6.07224768266113, 44.980208378415668 ], [ 6.0721827162449, 44.980210173298161 ], [ 6.072242397189464, 44.980140945582249 ], [ 6.07224964551812, 44.98004162966334 ], [ 6.072215383234463, 44.980024555236085 ], [ 6.072288104796636, 44.979860356805609 ], [ 6.072317251298561, 44.979697362268254 ], [ 6.072329447691141, 44.97961593066843 ], [ 6.072390413560169, 44.979555677874735 ], [ 6.072443366042548, 44.979450593887748 ], [ 6.072505929506852, 44.979318212772249 ], [ 6.072544672897946, 44.979200005571279 ], [

**CONTENT :**

No stack trace available

Request repr() unavailable.

**Comment by gutard** [comment]
Please could you search more information in geotrek log (complete error message) ?
Do you know what operation triggered this bug ?

**Comment by camillemonchicourt** [comment]
I was in holidays, no idea at all.
I will check if it happens again !

**Comment by gutard** [comment]
Please reopen if you reproduce and if you are able to provide more information
