### ISSUE TITLE
Notion de gestionnaire sur les contenus touristiques

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1396]
- Ajout des champs `description` et `pictogramme` sur la table existante `Organisme`,
- Ajout du champ `gestionnaire` N-N vers la table `Organisme` sur la table `Contenus touristiques`,
- Ajout des infos du gestionnaire (nom, description, logo) dans l'API JSON pour chaque contenu touristique.

@camillemonchicourt, @amandine-sahl, merci de confirmer que cette solution vous convient.

**Comment by camillemonchicourt** [comment]
C'est encore très discutable. :-)

**Comment by camillemonchicourt** [comment]
Notion abandonnée et remplacée par SOURCE, voir https://github.com/makinacorpus/Geotrek/issues/1354
