### ISSUE TITLE
Itinerancy

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1407]
- [X] add a new parent field
- [ ] sort by name
- [x] serialize parent/children
- [ ] publication of children in addition to publication of parents

**Comment by gutard** [comment]
Parent field and serialization released in v0.34.0

**Comment by camillemonchicourt** [comment]
When a parent is published, his detail page will include all his children (published or not). 
If you dont want to display children in RANDO homepage trek list, dont publish them. 
Now also available on Geotrek-mobile - https://github.com/makinacorpus/Geotrek-mobile/issues/109

#######################

The system is getting changed to associate children to parent and no more parent to children.
So it has to be done on parent form and no more on children form.
It allows to associate one children to several parents. 
It needs to include an `order` field and no more use alphabetical names to order children. 

See https://github.com/makinacorpus/Geotrek/issues/1479 for details.
