### ISSUE TITLE
Import touristics contents from Sitra

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1408]
- [ ] Import touristics contents from Sitra
- [ ] create another field which will held booking ID (identifiant de réservation ??)

**Comment by leplatrem** [comment]
Switch to français ?

J'imagine que vous avez plein de bonnes raisons, mais AMA, il vaut mieux garder l'anglais :) 

**Les plus**
* Ça entretient la pratique de cette merveilleuse langue :)
* Ça garantit l'international (ex. pour un étranger [voici l'effet que ça fait](https://github.com/Novik/ruTorrent/issues/531))
* Ça permet de faire copier-coller dans le changelog
* C'est la norme dans l'open source (pas sur l'adullact certes)

**Les moins**
* Ça exclut les non-anglophones de Github (*mais la mailing-liste pourrait être un peu plus vivante si les fonctionnalités étaient discutées là-bas en amont*)
* Ça finit toujours en franglais dans les commentaires (*dans ce cas au moins garder l'intitulé en anglais*)

...mais après tout ce n'est que mon avis :)

**Comment by SBats** [comment]
Mm we've just switched to French in some issues in rando in order to be able to exchange with Cevennes about the new version.
Though, I agree we should keep at least issues name in English. I'll edit the name of the issue.
Bu don't be afraid @leplatrem we're not going to do everything in French :P

**Comment by camillemonchicourt** [comment]
:-)
