### ISSUE TITLE
Problème d'installation 0.35 sur Ubuntu 14.04 (unicorn-geotrek.sock)

### ISSUE THREAD

**Issue by nicolas-ferchat** [makinacorpus/Geotrek#1467]
Bonjour,

Tout d'abord merci aux développeurs pour cette application super intéressante !!!

JPour ma part, je rencontre des soucis d'installation sous un Ubuntu 14.04 LTS. En effet, j'ai toujours l'erreur "Could not setup python environment !" lorsque j'exécute ./install.sh, quelque soit la version sauf la 0.35 (mais le souci est également présent sur la 0.35.1).

Sur la version 0.35 donc l'installation se déroule sans souci à priori, sauf que j'ai l'erreur "502 Bad Gateway" quand je me connecte sur la page principale (nom de mon serveur ou en localhost) avec nginx.

Je constate dans les logs d'erreur le message suivant 

2015/07/17 09:45:04 [crit] 22349#0: *14 connect() to unix:/home/Geotrek-master/var/run/gunicorn-geotrek.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /server-status?auto HTTP/1.1", upstream: "http://unix:/home/Geotrek-master/var/run/gunicorn-geotrek.sock:/server-status?auto", host: "127.0.0.1:80"

En effet le fichier gunicorn-geotrek.sock n'est pas présent dans le dossier, et ce malgré plusieurs installations, reboot.... 

Quelqu'un a-t-il déjà rencontré ce problème ?

Merci d'avance,

Nicolas

**Comment by camillemonchicourt** [comment]
Bonjour,

En effet la version 0.35.1 qui vient d'être publiée réglait un problème avec des dépendances sur un Ubuntu 12.04.

Des problèmes similaires viennent d'être largement discuté sur le  largement discuté sur le groupe GOOGLE : https://groups.google.com/forum/#!topic/geotrek-fr/hJxZWJ-_2sw
