### ISSUE TITLE
Handle multiple reservation systems

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1478]
- [ ] Add a new reservation_system field
- [ ] Add new field in API
- [ ] Allow to see/edit this field
- [ ] Ascending compat
- [ ] Documentation
- [ ] Test

**Comment by camillemonchicourt** [comment]
Yes, the new field reservation_system must be an external key based on a list of reservation system (OpenSystem / FFCAM / Gites de France actually).
