### ISSUE TITLE
Children treks ordering

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1479]
And allow one child in multiple parent treks

- [ ] Replace parent field by children one
- [ ] New widget
- [ ] Adapt exports, API
- [ ] Test
- [ ] Doc

**Comment by gutard** [comment]
@camillemonchicourt, is the user allowed to put any child trek in a parent trek ? Maybe it should be allowed to put only treks that belongs to its own structure.

**Comment by gutard** [comment]
@camillemonchicourt, another question : should we add a warning when the user deletes a child trek or just remove it silently from the parent trek ?

**Comment by camillemonchicourt** [comment]
Hum good question. 
It is like this in the MANAGEMENT modules (trails, signages, projects...) where everything is *structure related*
In the TREKS and TOURISM modules, 2 structures must be able to publish a global portal so they share the datas. Even if they can't edit datas of the other structure (except if bypass structure is activated for the user - https://github.com/makinacorpus/Geotrek/issues/1219).

I am not sure about the good answer. It would be easier for users to find a trek by only showing him treks from his own structure. But maybe I miss some cases. 
And as no list is *structure related* in the PUBLIC modules, maybe it is better to stay the same. 
How is it with related_treks ?

**Comment by camillemonchicourt** [comment]
I would say no warning as it is for other fields.
