### ISSUE TITLE
Multiple API instances with separate content

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1480]
In order to get multiple web portals with specific content.
Filtering by source ?
- [ ] Configuration
- [ ] New directory level in API
- [ ] Specific PDF template for each API instant (see #1229)
- [ ] Test
- [ ] Doc

**Comment by camillemonchicourt** [comment]
Yes filtering by source seems to be the most useful solution. 

The solution has to be configurable in order to choose which API get which sources.

Optionally, the case where filtering by structure can be included, at least planned.
