### ISSUE TITLE
Document how to import SITRA contents

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1482]
And give examples of code

**Comment by gutard** [comment]
Fixed in 2.8.0

**Comment by camillemonchicourt** [comment]
Some improvement to SITRA import have been done in 2.10.4 with : 
- https://github.com/makinacorpus/Geotrek/commit/2c9482ed25c2854d3585a944c54b9ff6cc93fefa
- https://github.com/makinacorpus/Geotrek/commit/a566cf31149a4c36af72877022f82691945c9d08
- https://github.com/makinacorpus/Geotrek/commit/5fbd50df1903693e35cd1512e46552f3656d3166

Some informations have added (such has additional phone number and address, many new fields in practical information and we can now set a default source for imported content from SITRA). 
A specific parser for Hebergement from SITRA has also been added (https://github.com/makinacorpus/Geotrek/blob/2c9482ed25c2854d3585a944c54b9ff6cc93fefa/geotrek/tourism/parsers.py#L149), it includes imported datas directly in Hebergements category from Geotrek touristic content. 

One thing that could be done would be to add reservation ID (and type of reservation system) i we find this field in SITRA (Apidae). 
And to import content in English too.
