### ISSUE TITLE
Import produits marqués esprit parc national / Format

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1485]
Les parcs nationaux prévoient de pouvoir importer des contenus touristiques depuis leur BDD commune PRODUITS_MARQUES.

Après comparaison des objets, voila ce qui en ressort en terme de correspondance de champs : 

![geotrek_marque](https://cloud.githubusercontent.com/assets/4418840/9854245/19a38f28-5b08-11e5-9fe3-781ec599659c.png)

Un flux par parc, avec la possibilité de filtrer pour limiter seulement à certains types ou sous-types.

Le format préféré étant le JSON, y a t-il une structuration spécifique du flux à fournir ?

**Comment by gutard** [comment]
Le plus basique convient très bien:
```json
[
    {
        "type": "...",
        "sousType": "...",
        ...
    },
    ...
]
```

Si le nombre d'éléments est important et qu'il faut faire de la pagination, on peut rajouter un niveau d'information pour donner le nombre d'éléments:
```json
{
    "numFound": 4231,
    "first": 1,
    "count": 100,
    "data": [
        {
            "type": "...",
            "sousType": "...",
            ...
        },
        ...
    ]
}
```

**Comment by camillemonchicourt** [comment]
OK merci !

**Comment by gutard** [comment]
Penser à mettre le champ label à True

**Comment by camillemonchicourt** [comment]
Le flux a été complété pour pouvoir filter par parc mais aussi éventuellement par type et sous-types de produits.

Sur la méthode "getProduitsSelonParc" :
- Attention j'ai modifié la codification des types et des sous-types pour une meilleure compréhension.
- Rajout du paramètre "typologie".

Rajout de la méthode "getTypologieProduits" pour pouvoir consulter les types et sous-types disponibles.

**Comment by gutard** [comment]
http://gestion.espritparcnational.com/ws/?f=getProduitsSelonParc&codeParc=PNE

**Comment by gutard** [comment]
Il n'est pas possible d'importer les dates de création et de modification car elles sont sous le contrôle générique (identique pour tous les objets) de Geotrek (en fait de PostgreSQL). Ce sont donc les dates de création et de modification *par le script d'import* qui seront enregistrées. Sauf lors de l'import initial, si l'import est lancé régulièrement, les dates seront quand même très proches.

**Comment by camillemonchicourt** [comment]
Ah ouais OK en effet !

**Comment by gutard** [comment]
Fixed in version 2.9.0

**Comment by camillemonchicourt** [comment]
RAPPEL : 

La version 2.10.2 de Geotrek-Admin corrige les problèmes ci-dessous :
- L'import restaure les contenus supprimés (si l'objet est toujours présent côté EPN mais qu'il a été supprimé côté Geotrek-admin, donc passé à supprime = True),
- Il signale les valeurs manquantes de type1/type2.

Si l'on veut forcer la valeur de category, il fait reprendre l'ensemble des attributs suivants :
    constant_fields = {
        'category': u"Produits du terroir",
        'published': True,
        'approved': True,
        'deleted': False,
    }

Voir https://geotrek.readthedocs.io/en/master/import.html#configure-marque-esprit-parc-import
