### ISSUE TITLE
How to activate IMPORT menu ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1486]

**Comment by gutard** [comment]
It is activated by default if you are superuser.

**Comment by camillemonchicourt** [comment]
OK thanks, I will try that.

**Comment by camillemonchicourt** [comment]
OK I didnt found it as it is not included in 2.0.0 that is the latest release.
I found that it is in a commit after this latest release - https://github.com/makinacorpus/Geotrek/commit/84ba987a03b3e51bd2dd17c1230c4073f50f8852
