### ISSUE TITLE
QUESTION - Touristic content and event still experimental ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1487]
Should we still use this setting to activate them or should these 2 modules be included in Geotrek-admin by default ?

**Comment by gutard** [comment]
We should include them by default. I put this in backlog so you can select it for a next sprint if you want.

**Comment by camillemonchicourt** [comment]
==> PNC

**Comment by gutard** [comment]
Just 2 lines to change. No need for tests (it's already tested). I'll do it for free ;)
