### ISSUE TITLE
Protect APIs

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek#1492]
@camillemonchicourt, what do you want exactly to protect ?

We can make an exhaustive check but I think that all data accessible without login and without access rights is public data.

**Comment by camillemonchicourt** [comment]
OK I had in mind that they shouldnt be accessible to anyone that has the URL.
Maybe something like an API KEY but indeed as public datas, it may dont make sense. 
But not sure we can allow anyone to use them as he wants. 
To be discussed.

**Comment by camillemonchicourt** [comment]
OK to let it open.
