### ISSUE TITLE
Add CONDITION field in INFRASTRUCTURE table

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1494]
So it would be available in SIGNAGE and INFRASTRUCTURE modules.
"Etat" in French.
It would be a list of values. 

So in DB it would add : 

- `etat` field in `gestion.a_t_amenagement` (Foreign key)
- `gestion.a_b_etat` table (id, structure, etat)

Also to be included in detail pages, detail and list exports and filters. 

PS : We would also need it in Geotrek-admin V1.X so need to discuss if it is possible to deploy in V1 and V2.

**Comment by camillemonchicourt** [comment]
OK in V 2.1.0 but isnt displayed in SIGNAGES and INFRASTRUCTURES filters.

**Comment by gutard** [comment]
However, "filter" was written down on my paper but I forgot it.
