### ISSUE TITLE
Versions prefix / Installation

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1505]
Maybe it would be better to use v prefix again for next versions in order to don't update the instal.sh script  (see https://groups.google.com/forum/#!msg/geotrek-fr/C3xaNDzyFsw/jEw4mmBtAAAJ) and also be compliant with update documentation (http://geotrek.readthedocs.org/en/latest/installation.html#software-update).

**Comment by gutard** [comment]
This is a matter of taste. The v prefix was required by semver 1.0.0 but is no more required by semver 2.0.0.
