### ISSUE TITLE
MAP EXPORT in PDF - Different basemap depending on structure

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1527]
PNM / PNAM are working on the same Geotrek. 
But IGN is doing well on PNM (FR) while it is not good on PNAM (IT). 
When using maps in Geotrek-admin, they can choose the basemap to display (IGN, OSM...) so it is working well. 
Same when exporting a map from Geotrek-admin, it uses the basemap displayed. 

But when it is about exporting ODT, PDF or DOC, they can't choose which basemap is used. 

An idea would be to have a basemap when exporting PNM objects (IGN) and another one when exporting PNAM objects (OSM for example).

**Comment by gutard** [comment]
This works (correctly) since release 2.7.1 with FORCED_LAYERS setting
