### ISSUE TITLE
Question - QUERY to get all POIs related to a trek

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1528]
While it uses dynamic segmentation, I am looking for the query to get ALL pois related to a trek. 
This would be useful for other cases (signages related to a trail....) .

Can someone help me or tell me to find it in the Geotrek code ?

Thanks.

**Comment by gutard** [comment]
This code is written in Python language (django ORM), not in SQL

**Comment by camillemonchicourt** [comment]
Hum yes I understand but I thought that findind the ORM part of code would help me to translate it in SQL?

**Comment by gutard** [comment]
This line adds the pois property to all topologies (including treks):
https://github.com/makinacorpus/Geotrek/blob/master/geotrek/trekking/models.py#L617

topology_pois() is defined just before:
https://github.com/makinacorpus/Geotrek/blob/master/geotrek/trekking/models.py#L601

which calls:
https://github.com/makinacorpus/Geotrek/blob/master/geotrek/core/models.py#L269

which calls:
https://github.com/makinacorpus/Geotrek/blob/master/geotrek/core/helpers.py#L204

Actually, there is some SQL code here.

**Comment by camillemonchicourt** [comment]
OK thanks a lot !

**Comment by camillemonchicourt** [comment]
OK I am bad in SQL and even worst in Python. :-)
So we checked the links with @amandine-sahl and finally did like this to get all POIs from a trek : 

WITH etrek AS (
	SELECT *
	FROM geotrek.e_r_evenement_troncon
	WHERE evenement IN (
		SELECT id 
		FROM geotrek.e_t_evenement
		WHERE kind = 'TREK' AND supprime = false
	)
), epoi AS (
	SELECT *
	FROM geotrek.e_r_evenement_troncon
	WHERE evenement IN (
		SELECT id 
		FROM geotrek.e_t_evenement
		WHERE kind = 'POI' AND supprime = false
	)
)
SELECT DISTINCT et.evenement, p.* 
FROM etrek et
JOIN epoi ep
ON et.troncon = ep.troncon 
	AND (
	 (et.pk_debut <= et.pk_fin AND ep.pk_debut between et.pk_debut AND et.pk_fin) 
	 OR 
	 (et.pk_debut > et.pk_fin AND ep.pk_debut between et.pk_fin  AND et.pk_debut) 
	)
JOIN  rando.o_t_poi  p
ON p.evenement = ep.evenement
WHERE et.evenement = 903303
ORDER BY p.nom

**Comment by samuelpriou** [comment]
Thank you. Very convenient !

**Comment by camillemonchicourt** [comment]
Dans la même logique, si je veux tous les panneaux d'un sentier (921423) : 

````SQL
WITH etrail AS (
	SELECT *
	FROM geotrek.e_r_evenement_troncon
	WHERE evenement IN (
		SELECT id 
		FROM geotrek.e_t_evenement
		WHERE kind = 'TRAIL' AND supprime = false
	)
), esign AS (
	SELECT *
	FROM geotrek.e_r_evenement_troncon
	WHERE evenement IN (
		SELECT id 
		FROM geotrek.e_t_evenement
		WHERE kind = 'SIGNAGE' AND supprime = false
	)
)
SELECT et.evenement, s.* 
FROM etrail et
JOIN esign es
ON et.troncon = es.troncon 
	AND (
	 (et.pk_debut <= et.pk_fin AND es.pk_debut between et.pk_debut AND et.pk_fin) 
	 OR 
	 (et.pk_debut > et.pk_fin AND es.pk_debut between et.pk_fin  AND et.pk_debut) 
	)
JOIN  gestion.a_t_amenagement  s
ON s.evenement = es.evenement
WHERE et.evenement = 921423
ORDER BY s.nom
````

**Comment by gutard** [comment]
I close since the question was answered
