### ISSUE TITLE
Import and unpublished objects

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1596]
When importing from SIT, it would be useful to be able to unpublish some objects one by one (duplicate objects, not interesting objects...). 
But actually if you unpublish an object, the next import will republish it. 

The idea would be to publish by default new imported objects, but not to republish existing object.

**Comment by submarcos** [comment]
There are options to configure it.

By default you would have in your parser: 

```
constant_fields = {
    ...,
    'published': True,
    ...,
}
```

 which apply published = True on each parsed element. (olds and news)

You can apply your own process by removing this field like this
```
constant_fields = {
    ...
}
```

and wrote a custom filter to publish element:
```
def filter_published(self, src, val):
     # check if element already exists
     if exists:
         return element.published
    else:
        return True
```

Or something like that

http://geotrek.readthedocs.io/en/master/import.html#configure-sitra-import

**Comment by camillemonchicourt** [comment]
OK thanks but where to include the custom filter ?

**Comment by submarcos** [comment]
Ok, my idea was good but there is an exception for 'published'

to do that, don't override filter_published but do that like this (in bulkimports.parsers.XXXPARSER):

```
class CustomParser(BaseParser):
    .....
   # make sure constant_fields has not 'published' in its keys
   constant_fields = {
   }

   # ovveride this method
   def parse_obj(self, row, operation):
        if not self.obj.pk:
            self.obj.published = True
       super(CustomParser, self).parse_obj(row, operation)
```

take care of super() function, CustomParser must be replaced by your class name

tested on a real parser

**Comment by camillemonchicourt** [comment]
I tried to make an import, unpublish one touristic content, relaunch parser but the touristic content was re-published. 
Maybe I didnt put the methode overriding at the right place.

My `/bulkimportparsers.py` : 

```Python
from geotrek.tourism.parsers import HebergementsSitraParser

class HebergementParser(HebergementsSitraParser):
    label = u"Hebergements PNE APIDAE"
    api_key = '4VcrzLCH'
    project_id = 1510
    selection_id = 37078
    source = ['Apidae']
# override this method
    def parse_obj(self, row, operation):
        if not self.obj.pk:
            self.obj.published = True
        super(HebergementParser, self).parse_obj(row, operation)
```

**Comment by submarcos** [comment]
you need to add :
```
   ***
   constant_fields = {
   }
   ***
```
like my previous exemple.

**Comment by camillemonchicourt** [comment]
OK perfect, I understand, tried it and it works ! 
Thanks.
