### ISSUE TITLE
Export to cirkwi / espace loisir IGN

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek#806]

**Comment by camillemonchicourt** [comment]
Les flux ont été mis à jour avec les évolutions prévues ("Il n’y aura plus les étapes et une trace par étape mais une trace toute seul + des pois liés + des informations de parcours").

Les circuits touristiques : http://ws.cirkwi.com/tuto/flux_circuits/
Les points d'intérêt : http://ws.cirkwi.com/tuto/flux_pois/

**Comment by camillemonchicourt** [comment]
2 points à prendre en compte.
Le volet multilingues et voir comment on fait correspondre les valeurs de nos typologies aux leurs. 
J'imagine par exemple qu'ils n'ont pas les mêmes types de POI que nous avons au PNE et qui sont aussi différentes dans un autre parc...
J'attends des infos de l'IGN concernant les différentes typologies.

J'attends aussi un retour de leur part car il semble manquer de nombreuses informations dans leur flux, pourtant présentes dans leurs fiches (difficulté, durée, type de parcours, dénivelé, usages...

**Comment by camillemonchicourt** [comment]
A noter aussi que l'on souhaiterait ajouter dans les descriptif l'URL de la fiche rando SOURCE.

Exemple de code qui pourrait ajouter dans la balise <description> : 
<p><u>Source</u> : <a href="http://rando.ecrins-parcnational.fr/fr/boucle-du-pigeonnier-dans-le-cirque-du-gioberney" target="_blank">http://rando.ecrins-parcnational.fr/fr/boucle-du-pigeonnier-dans-le-cirque-du-gioberney</a>

A discuter selon la faisabilité.

**Comment by camillemonchicourt** [comment]
Quelques précisions fournies par l'IGN : 

Les notions de difficulté et durée, se trouvent dans les balises de Locomotion : 
<locomotions>
<locomotion type="voiture" id_locomotion="2" difficulte="1" duree="45"></locomotion>
<locomotion type="vtt" id_locomotion="3" difficulte="3" duree="129"></locomotion>
</locomotions>

Une petite précision toutefois sur les notions de "type de parcours" et "usage".

Nous avons le champ ID-LOCOMOTION qui correspond à la notion de loisirs / locomotion à savoir engins motorisés, a pied, a cheval, sports nautiques, etc...
Nous avons le champs TYPE qui correspond à la sous-catégorie de loisirs (ou usage) à savoir VTT, Trail, randonnée pédestre, etc...

Le champs DENIVELE, sera calculé par l'Espace loisirs à partir de la donnée transmise en appui sur ses outils (webservices IGN, et outils Cirkwi) et procédera au renseignement de cette information.

**Comment by camillemonchicourt** [comment]
Voici donc les correspondances des champs entre Geotrek et IGN : 

- Pratique >> locomotion/loisirs
- Themes >> thematiques/tags
- Types de POI >> Categories POI

Les valeurs de ces champs côté IGN sont listés ici : http://ws.cirkwi.com/tuto/categories.php

**Comment by camillemonchicourt** [comment]
En plus des POI patrimoniaux, il serait pertinent de faire remonter les LIEUX DE RENSEIGNEMENT en les envoyant avec les autres POI dans la catégorie INFORMATIONS

```
<categorie_poi nom="Informations">
    <sous_categorie nom="Offices de tourisme" id_categorie="23"/>
    <sous_categorie nom="Autres informations" id_categorie="79"/>
</categorie_poi>
```

**Comment by camillemonchicourt** [comment]
Included since 0.32.0, fixed in 0.33.x

- [URL]/api/cirkwi/circuits.xml
- [URL]/api/cirkwi/pois.xml

Discussed in https://groups.google.com/forum/#!topic/geotrek-fr/6DiLkEIdOq4

**Comment by camillemonchicourt** [comment]
L'Espace Loisirs change de nom et s'appelle désormais IGNrando'
