### ISSUE TITLE
Support vectorial pictograms (themes, usages, POI types, weblink categories...)

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek#964]
Take care of : 

* ODT Template inclusion 
* SVG to PNG conversion using ConvertIt (like altimetric profiles)

Probably get rid of : 

* https://github.com/makinacorpus/Geotrek/blob/master/geotrek/trekking/models.py#L587-L607

Related : https://github.com/makinacorpus/Geotrek-rando/issues/111

**Comment by gutard** [comment]
In v2 pictograms are SVG
